### ISSUE TITLE
May I know its difference with ULIP?

### ISSUE THREAD

**Issue by chenxinli001** [UCSC-VLAA/MixCon3D#1]

**Comment by gaoypeng** [comment]
Hi! Thanks for your interest in our work. We list both the technical and methodological differences below:

1) We systematically analyze the effect of the training recipe. The results are shown in Table 2 and appendix.

2) For the method, ULIP simply aligns the point to image and text independently, while our work explores the importance of building a more holistic representation in the contrastive training paradigm, i.e., using multi-view images and point cloud to build 3D object-level representation and performing 3D-to-text alignment.

Free free to contact me if any further questions :)

**Comment by chenxinli001** [comment]
Thanks, bro
