### ISSUE TITLE
About the data

### ISSUE THREAD

**Issue by eriche2016** [UCSC-VLAA/MixCon3D#2]
Hi, excellent work. 
I have a question regarding the data. 
I have downloaded the rendered images(https://huggingface.co/datasets/OpenShape/openshape-training-data/tree/main/rendered_images), however, I cannot unzip some .tar.gz files successfully. I guess these files are broken. 
So have you used these raw images  for training?  If not, I will skip this part.

**Comment by gaoypeng** [comment]
Hi! Sorry for the late reply and any inconvenience. For this codebase, we don't need the raw images for training and I use the extracted features for training. The data preparation process is the same as OpenShape. Feel free to reach out if any other questions.
